---
title: "discordance_paper_results"
output: html_document
date: "2024-11-14"
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("~/Downloads/fnih_plasma_platform_discordance.R")
```

## R Markdown

```{r agreement plots 1, echo=FALSE}
cubbt_ab_pos_agreement_matrix_ab_ratio_plot
```

```{r agreement plots 2, echo=FALSE}
cubbt_ab_pos_agreement_matrix_plus_gold_standard_ab_ratio_plot
```

```{r agreement plots 3, echo=FALSE}
cubbt_ab_pos_true_agreement_ab_ratio_plot
```

```{r agreement plots 4, echo=FALSE}
cubbt_ab_pos_agreement_matrix_ptau217_plot
```

```{r agreement plots 5, echo=FALSE}
cubbt_ab_pos_agreement_matrix_plus_gold_standard_ptau217_plot
```

```{r agreement plots 6, echo=FALSE}
cubbt_ab_pos_true_agreement_ptau217_plot
```

```{r agreement plots 7, echo=FALSE}
cubbt_tau_pos_agreement_matrix_ptau217_plot
```

```{r agreement plots 8, echo=FALSE}
cubbt_tau_pos_agreement_matrix_plus_gold_standard_ptau217_plot
```

```{r agreement plots 9, echo=FALSE}
cubbt_tau_pos_true_agreement_ptau217_plot
```

```{r AB PET ~ AB42/40 tables, echo=FALSE}
count_ab_ratio_ab_pet_correct_tbl
c2n_ab_ratio_ab_pet_correct_tbl
fuji_ab_ratio_ab_pet_correct_tbl
quanterix_ab_ratio_ab_pet_correct_tbl
roche_ab_ratio_ab_pet_correct_tbl
```

```{r AB PET ~ p-tau tables, echo=FALSE}
count_ptau217_ab_pet_correct_tbl
c2n_ptau217_ab_pet_correct_tbl
fuji_ptau217_ab_pet_correct_tbl
alzpath_ptau217_ab_pet_correct_tbl
janssen_ptau217_ab_pet_correct_tbl
c2n_ptau_ratio_ab_pet_correct_tbl
```

```{r Early Tau PET ~ p-tau tables, echo=FALSE}
count_ptau217_tau_pet_correct_tbl
c2n_ptau217_tau_pet_correct_tbl
fuji_ptau217_tau_pet_correct_tbl
alzpath_ptau217_tau_pet_correct_tbl
janssen_ptau217_tau_pet_correct_tbl
c2n_ptau_ratio_tau_pet_correct_tbl
```

```{r mediation results, echo=FALSE}
summary(mediation_results_c2n)
summary(mediation_results_fuji)
summary(mediation_results_janssen)
summary(mediation_results_alzpath)
```

```{r comparison of accuracy, echo=FALSE}
centiloid_ab_ratio_ptau_comparison_plot
centiloid_ab_ratio_ptau_comparison_df

```
